### ISSUE TITLE
Solicitud de incorporación

### ISSUE THREAD

**Issue by gus0117** [mamanidario19/devtech-podcast-web#1]
## Solicitud de incorporación.

Hola Darío soy Gustavo Ordoñez, te solicito incorporarme al proyecto 😁.

![image](https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif)

### Modificaciones que propongo

- Agregaré un nuevo asset para mi avatar de Avatar Maker y una descripción mia.
- Modificare una tarjeta para que quede tal cual así:

![image](https://user-images.githubusercontent.com/49104263/178356925-ea98bcf4-5131-4b24-8081-e06fef4d584c.png)

### Enlaces

- Extención de google chrome: https://chrome.google.com/webstore/detail/avatar-maker/ofknlbikfofijlcjkfcihomkedmchfbn

Saludos! 👍

**Comment by mamanidario19** [comment]
## Solicitud Aprobada #1 

Saludos Gustavo @gus0117  ! gracias por avisar, espero tu modificaciones en la tarjeta numero 2, muy buena la extensión para generar avatar! 
![image](https://user-images.githubusercontent.com/32744941/178358764-c0c7feda-9683-4e57-92b7-67ea18222df0.png)

Exitos! Atte.- Dario.
