### ISSUE TITLE
Solicitud de incorporación como miembro del equipo del podcast DevTech

### ISSUE THREAD

**Issue by alecio87** [mamanidario19/devtech-podcast-web#2]
## Solicitud de incorporación.

Hola @mamanidario19   soy Emanuel Ibañes, te solicito incorporarme como miembro del equipo al proyecto 😁😁.
![image](https://media.giphy.com/media/QX6ruFElzFdeIfblrg/giphy.gif)

### Modificaciones que propongo

- Agregaré un nuevo asset para mi avatar de Avatar Maker y una descripción mia.
- Modificare una tarjeta para que quede tal cual así:

![image](https://user-images.githubusercontent.com/21963028/178361959-73208135-a844-434d-ac9a-a1b947539a07.png)

### Enlaces
- [Extención de google chrome](https://chrome.google.com/webstore/detail/avatar-maker/ofknlbikfofijlcjkfcihomkedmchfbn)

**Comment by mamanidario19** [comment]
## Solicitud Aprobada #2 
Saludos Emanuel @alecio87 ! gracias por comunicarte, espero tu modificaciones en la tarjeta numero 3. Cualquier duda puedes consultarme. 
![image](https://user-images.githubusercontent.com/32744941/178363298-ceefdb21-f218-4c26-9880-ef381b768e2e.png)
Suerte! 

Atte.- Dario
